document.writeln("<!--对联悬浮广告开始-->");
document.writeln("<style type=\'text/css\'>");
document.writeln("*{margin:0;padding:0;list-style-type:none;}");
document.writeln(".fixediv{position:fixed;top:140px;z-index:9999;width:400px;height:300px;background:#ddd;}");
document.writeln(".fixediv img{float:left;}");
document.writeln(".fixediv a.close{display:block;height:30px;line-height:30px;background:#fff;font-size:14px;padding:0 10px;color:#5e5e5e;text-decoration:none;text-align:center;}");
document.writeln(".leftadv{left:0px;}");
document.writeln(".rightadv{right:0px;}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div class=\'fixediv leftadv\'>");
document.writeln("	<a href=\'\'><img src=\'http://qicheyongpin.cc/images/180.jpg\' width=\'400\' height=\'300\' alt=\'新锦江娱乐\' /></a>");
document.writeln("	<a class=\'close\' href=\'javascript:void(0);\'>关闭广告</a>");
document.writeln("</div>");
document.writeln("");
document.writeln("<div class=\'fixediv rightadv\'>");
document.writeln("	<a href=\'\'><img src=\'http://qicheyongpin.cc/images/280.jpg\' width=\'400\' height=\'300\' alt=\'新锦江娱乐\' /></a>");
document.writeln("	<a class=\'close\' href=\'javascript:void(0);\'>关闭广告</a>");
document.writeln("	");
document.writeln("	<div style=\'padding-top:310px;\'>   </div>");
document.writeln("	<a href=\'http://www.xjj6789.com/\' target=\'_blank\'><img src=\'http://qicheyongpin.cc/images/game.png\' width=\'400\' height=\'171\' alt=\'新锦江娱乐\' /></a>");
document.writeln("	");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<script type=\'text/javascript\' src=\'http://qicheyongpin.cc/images/js/jquery-1.4.2.min.js\'></script>");
document.writeln("");
document.writeln("<script type=\'text/javascript\' src=\'http://qicheyongpin.cc/images/js/float.js\'></script>");
document.writeln("<!--对联悬浮广告结束-->");